"""add_image_url_to_markets_and_communities

Revision ID: 71f372c1e025
Revises: 5dbff09613a4
Create Date: 2025-11-07 15:12:03.097776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71f372c1e025'
down_revision = '5dbff09613a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # Add columns only if they don't exist
    community_columns = [col['name'] for col in inspector.get_columns('communities')]
    if 'image_url' not in community_columns:
        op.add_column('communities', sa.Column('image_url', sa.String(), nullable=True))

    market_columns = [col['name'] for col in inspector.get_columns('markets')]
    if 'image_url' not in market_columns:
        op.add_column('markets', sa.Column('image_url', sa.String(), nullable=True))

    # Drop indexes only if they exist
    existing_indexes = inspector.get_indexes('orders')
    if any(idx['name'] == 'ix_orders_market_outcome' for idx in existing_indexes):
        op.drop_index('ix_orders_market_outcome', table_name='orders')

    existing_indexes = inspector.get_indexes('positions')
    if any(idx['name'] == 'ix_positions_market_outcome' for idx in existing_indexes):
        op.drop_index('ix_positions_market_outcome', table_name='positions')

    existing_indexes = inspector.get_indexes('trades')
    if any(idx['name'] == 'ix_trades_market_outcome' for idx in existing_indexes):
        op.drop_index('ix_trades_market_outcome', table_name='trades')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_trades_market_outcome', 'trades', ['market_id', 'outcome_name', 'outcome'], unique=False)
    op.create_index('ix_positions_market_outcome', 'positions', ['market_id', 'outcome_name', 'outcome'], unique=False)
    op.create_index('ix_orders_market_outcome', 'orders', ['market_id', 'outcome_name', 'outcome'], unique=False)
    op.drop_column('markets', 'image_url')
    op.drop_column('communities', 'image_url')
    # ### end Alembic commands ###
