"""add_image_url_to_markets_and_communities

Revision ID: 71f372c1e025
Revises: 5dbff09613a4
Create Date: 2025-11-07 15:12:03.097776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71f372c1e025'
down_revision = '5dbff09613a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('markets', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_index('ix_orders_market_outcome', table_name='orders')
    op.drop_index('ix_positions_market_outcome', table_name='positions')
    op.drop_index('ix_trades_market_outcome', table_name='trades')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_trades_market_outcome', 'trades', ['market_id', 'outcome_name', 'outcome'], unique=False)
    op.create_index('ix_positions_market_outcome', 'positions', ['market_id', 'outcome_name', 'outcome'], unique=False)
    op.create_index('ix_orders_market_outcome', 'orders', ['market_id', 'outcome_name', 'outcome'], unique=False)
    op.drop_column('markets', 'image_url')
    op.drop_column('communities', 'image_url')
    # ### end Alembic commands ###

